# Generated by Django 5.0.2 on 2024-03-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquatorProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='N/A', max_length=25)),
                ('property_url', models.CharField(blank=True, max_length=500)),
                ('street_name', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip', models.CharField(blank=True, max_length=5)),
                ('county_name', models.CharField(blank=True, max_length=100)),
                ('listed_price', models.CharField(blank=True, max_length=100)),
                ('year_built', models.CharField(blank=True, max_length=4)),
                ('property_type', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('bedroom', models.CharField(blank=True, max_length=10)),
                ('bathroom', models.CharField(blank=True, max_length=10)),
                ('square_ft', models.CharField(blank=True, max_length=10)),
                ('lot_size_sqft', models.CharField(blank=True, max_length=10)),
                ('lot_size_acre', models.CharField(blank=True, max_length=10)),
                ('has_basement', models.CharField(blank=True, max_length=1)),
                ('has_ac', models.CharField(blank=True, max_length=1)),
                ('has_pool', models.CharField(blank=True, max_length=1)),
                ('estimated_cashflow', models.CharField(blank=True, max_length=10)),
                ('estimated_gross_yield', models.CharField(blank=True, max_length=10)),
                ('estimated_net_yield', models.CharField(blank=True, max_length=10)),
                ('mls_number', models.CharField(blank=True, max_length=20)),
                ('realty', models.CharField(blank=True, max_length=100)),
                ('agent_name', models.CharField(blank=True, max_length=100)),
                ('agent_email', models.CharField(blank=True, max_length=100)),
                ('agent_phone', models.CharField(blank=True, max_length=100)),
                ('photo_one', models.CharField(blank=True, max_length=275)),
                ('photo_two', models.CharField(blank=True, max_length=275)),
                ('photo_three', models.CharField(blank=True, max_length=275)),
                ('insert_dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
