# Generated by Django 5.0.2 on 2024-03-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreclosure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtorProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='N/A', max_length=25)),
                ('property_url', models.CharField(blank=True, max_length=500)),
                ('street_name', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip', models.CharField(blank=True, max_length=5)),
                ('county_name', models.CharField(blank=True, max_length=100)),
                ('listed_price', models.CharField(blank=True, max_length=100)),
                ('year_built', models.CharField(blank=True, max_length=4)),
                ('property_type', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('bedroom', models.CharField(blank=True, max_length=10)),
                ('bathroom', models.CharField(blank=True, max_length=10)),
                ('square_ft', models.CharField(blank=True, max_length=10)),
                ('stories', models.CharField(blank=True, max_length=1)),
                ('garage', models.CharField(blank=True, max_length=1)),
                ('lot_size_sqft', models.CharField(blank=True, max_length=10)),
                ('monthly_payment', models.CharField(blank=True, max_length=10)),
                ('principal_and_interest', models.CharField(blank=True, max_length=1)),
                ('home_insurance', models.CharField(blank=True, max_length=10)),
                ('hoa_fees', models.CharField(blank=True, max_length=10)),
                ('property_tax', models.CharField(blank=True, max_length=10)),
                ('agent_name', models.CharField(blank=True, max_length=20)),
                ('agent_email', models.CharField(blank=True, max_length=100)),
                ('property_image', models.CharField(blank=True, max_length=275)),
                ('insert_dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
