# Generated by Django 5.0.2 on 2024-03-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreclosure', '0002_realtorproperties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtorproperties',
            name='principal_and_interest',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
