# Generated by Django 5.0.2 on 2024-03-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreclosure', '0003_alter_realtorproperties_principal_and_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtorproperties',
            name='garage',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='realtorproperties',
            name='stories',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
