# Generated by Django 5.0.2 on 2024-03-17 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foreclosure', '0004_alter_realtorproperties_garage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtorproperties',
            old_name='property_image',
            new_name='photo_one',
        ),
    ]
