# Generated by Django 5.0.2 on 2024-03-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreclosure', '0005_rename_property_image_realtorproperties_photo_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtorproperties',
            name='agent_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
